version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ai-commit
    binary: ai-commit
    main: ./cmd/
    ldflags:
      - "-X github.com/theburrowhub/ai-commit/internal/version.version={{.Version}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - ai-commit

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: theburrowhub
    name: ai-commit
  draft: false
  prerelease: auto

dockers:
  - image_templates:
      - "ghcr.io/theburrowhub/ai-commit:{{ .Version }}"
      - "{{ if not .Prerelease }}ghcr.io/theburrowhub/ai-commit:latest{{ end }}"
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--build-arg=APP_VERSION={{.Version}}"
